const data = [
  {
    id: "1",
    title: "Grand Theft Auto V",
    release_date: "April 14th, 2015",
    genre: " Action, Racing, 3D",
    developer_publisher: "Rockstar games",
    platform: "PC (Windows)",
    multiplayer: "Available (version 1.68)",
    version: "1.0.3095",
    size: "61 GB",
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2017/09/gta-v-poster.jpg",
      bg_large: "https://wallpapercave.com/wp/wp1809630.jpg",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/gta-v-screenshot-08.jpg",
    ],
    download_links: {
      gdrive:
        "https://drive.google.com/file/d/1cXdUi8D_RAfZ3eKvSo9qw_8BYKqOacpE/view",
      torrent: "https://se7en.ws/torrents/gtav_latest.torrent",
      mega: "https://mega.nz/file/TI8kmA5T#nDa78GKC0b933PfDJf7Me0yo6RzuF4T9HRz4OQLSuI4",
      directly: "https://se7en.ws/files/7l_gtav_setup.exe",
    },
    description: [
      "Los Santos is a radiant city of starlets and already shining stars. Erstwhile city was the envy of the whole westworld. For now it’s a shelter for dirty reality shows choking in the vise of economic difficulties. At the center of all events – trio of completely different offenders who tries to catch the luck in unceasing struggle for a place under the sun. Ex-member of the street gang Franklin tries to quit his past. A retired bank robber Michael discovers that in an honest life everything is not as rosy as imagined. Trevor – fan of violence and psycho who tries himself in several busineses in hoping of large jackpot. When they were exhausting of options they risk of their lives, make a series of daring robberies with only way to have all or nothing.",
      "In GTA 5 you can see the largest and the most detailed world ever created by Rockstar Games. Also the opportunity to influence the life and actions of three main characters. This combination of several characters history will make the game as exciting and fascinating as possible.",
      "You can find all of attributes from famous series of GTA in this part of the game. There are unbelieveble attention to details, elegant black humor, mockery of the pop-culture, and even absolutely new entertaining multiplayer mode.",
    ],
    minimum_requirements: [
      "OS: Windows 10 64 Bit",
      "Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHz",
      "Memory: 4GB",
      "Video Card: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)",
      " Sound Card: 100% DirectX 10 compatible",
      "HDD Space: 65GB",
    ],
    recommended_requirements: [
      "OS: Windows 10 64 Bit",
      "Processor: Intel Core i5 3470 @ 3.2GHZ (4 CPUs) / AMD X8 FX-8350 @ 4GHZ (8 CPUs)",
      "Memory: 8GB",
      "Video Card: NVIDIA GTX 660 2GB / AMD HD7870 2GB",
      "Sound Card: 100% DirectX 10 compatible",
      "HDD Space: 65GB",
    ],
  },

  {
    id: "2",
    title: "Grand Theft Auto IV",
    release_date: "December 2, 2008",
    developer_publisher: "Rockstar games",
    genre: " Action, adventure",
    platform: "PC (Windows)",
    multiplayer: "included",
    version:
      "1.2.0.43 (Includes episodes “The Lost and Damned” and “The Ballad of Gay Tony”)",
    size: "12.7 GB",
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-cover.png",
      bg_large: "https://wallpaperset.com/w/full/1/e/c/230031.jpg",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/gta-iv-screenshot-08.jpg",
    ],
    download_links: {
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xaXNoRHc4ZFhyRnAzb2V5Ukx0cXFzeTdsYnJFTWdQMmkvdmlldz91c3A9c2hhcmVfbGluaw==",
      torrent: "https://se7en.ws/torrents/gtaiv_latest.torrent",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvd29veFFCb2IjM0FMaDd3UnR3SWZES1RLakc0VEJCdU03ZGRBeFhmWXJkLWs4cEY0NlY3RQ==",
      directly: "https://se7en.ws/files/7l_gtaiv_setup.exe",
    },
    description: [
      "GTA 4 — is a cross-platform 3D action-adventure game. Chronologically, it is the ninth in the famous Grand Theft Auto series. It was released on April 29, 2008 for game consoles, and a year later for personal computers. The game also has an add-on Episodes from Liberty City. At the disposal of the player received several new characters, a supplemented storyline and many side quests.",
      "On our site you can download GTA 4 torrent or directly through the browser. The client has a built-in launcher (7Launcher) to automatically update the game.",
    ],
    minimum_requirements: [
      "OS: Windows 10 64 Bit",
      "Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHz",
      "Memory: 2GB",
      "Video Card: 512MB NVIDIA 8600 / 512MB ATI 3870",
      "Sound Card: DirectX 9.0c Compliant Card, Windows-Compatible Sound Card",
      "HDD Space: 22GB",
      "Input: Mouse & Keyboard, Controller (recommended)",
      "",
    ],
  },

  {
    id: "3",
    title: "Forza Horizon 5",
    release_date: " November 9, 2021",
    genre: "Racing, Simulation, Adventure ",
    developer_publisher: "Playground Games & Xbox Game Studios",
    platform: "PC (Windows)",
    multiplayer: " Included",
    version: "1.628.420 (12/7/2023)",
    size: "100 GB",
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2022/10/forzah5-cover.png",
      bg_large: "https://images3.alphacoders.com/118/1180539.jpg",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-08.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-09.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-10.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-11.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/forza-horizon-5-screenshot-12.jpg",
    ],
    download_links: {
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xSGUwMUxEa0ZIcFIxWmdLWW9mNzRWSWt0WTFhMkV2NjIvdmlldz91c3A9c2hhcmVfbGluaw==",
      torrent: "https://se7en.ws/torrents/forzah5_latest.torrent",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvZDh3RXlKWlMjT1NFX29ULS1FU3pfSV9UaV96dWFESEZ4MDkya0xvMTZSZlQtTlVxZVJkWQ==",
      directly: "https://se7en.ws/files/7l_forzah5_setup.exe",
    },
    description: [
      "Forza Horizon 5 is an arcade racing game from the famous British developer Playground Games. The racing series is published by Xbox Game Studios. The game was announced in June 2021 at the annual gaming event E3.",
      "Racing project Forza Horizon 5 was presented at a joint event between Xbox and Bethesda for Windows platforms, next-gen consoles XBOX Series X / S, and XBOX One. During the development of the game, the developers wanted to create a large-scale map so that players could enjoy the scenery. But at the same time, Playground Games understood that the world should be not only big, but also diverse. Otherwise, there is little use from a large-scale map.",
    ],
    minimum_requirements: [
      "OS: Windows 10 (version 15063.0 and later)",
      "Processor: Intel i5-4460 or AMD Ryzen 3 1200",
      "RAM: 8 GB",
      "Video card: Nvidia GTX 970 or AMD RX 470",
      "Free disk space: 110 GB",
    ],
    recommended_requirements: [
      "OS: Windows 10 (version 15063.0 and later) / 11",
      "Processor: Intel i5-8400 or AMD Ryzen 5 1500X",
      "RAM: 16 GB",
      "Video card: Nvidia GTX 1070 or AMD RX 590",
      "Free disk space: 110 GB",
    ],
  },

  {
    id: "4",
    title: "CYBERPUNK 2077: ULTIMATE EDITION",
    release_date: "December 10, 2020",
    genre: " Action, RPG ",
    developer_publisher: " CD Projekt RED",
    platform: "PC (Windows)",
    multiplayer: "Present in test mode",
    version: "2.1 from 12/5/2023 (Phantom Liberty DLC included)",
    size: "",
    images: {
      poster:
        "https://se7en.ws/wp-content/uploads/2023/09/cyberpunk-2077-cover.png",
      bg_large:
        "https://c4.wallpaperflare.com/wallpaper/3/908/60/cyberpunk-2077-video-game-characters-hd-wallpaper-preview.jpg",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/cyberpunk-2077-screenshot-08.jpg",
    ],
    download_links: {
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xQ2p5NXdUM19HRWRyUE5lcjA4YVdheEtyMklFYWdGbjAvdmlldz91c3A9c2hhcmluZw==",
      torrent: "https://se7en.ws/torrents/cyberpunk2077_latest.torrent",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvVTlSMmpBZ0QjTEswdkZabmExREMtU0RIdjJvZHoybk9kenlaaDU0eGlTamxrQzRWRWQ1TQ==",
      directly: "https://se7en.ws/files/7l_cyberpunk2077_setup.exe",
    },
    description: [
      "Cyberpunk 2077 is a cross-platform game from publishers CD Projekt RED, which is known for The Witcher project. “Cyberpunk 2077” is a sequel to the board game of the same name. Game actions develop in the city of Night City, 57 years after the plot of “Cyberpunk 2020”. The main character Vee finds himself in the dystopian West Coast. Overall, the game is the opposite of utopia and shows real life in North America.",
      "You create your own hero. Unlike The Witcher, Cyberpunk 2077 provides a flexible character editor. There are a number of classes to choose from, which can be combined with each other. The game’s emphasis is on realism, meaning that if a bullet hits an arm or leg, the character can lose the wounded limb. Phantom Liberty update was recently released, which opens up new horizons for the world of technocracy.",
    ],
    minimum_requirements: [
      "OS: Windows 10 (64 bit);",
      "Processor: Intel Core i7-6700 or AMD Ryzen 5 1600;",
      "RAM: 12 GB;",
      "Graphics card: GeForce GTX 1060 6GB, Radeon RX 580 8GB or Arc A380;",
      "Disk space: 85 GB (SSD).",
    ],

    recommended_requirements: [
      "OS: Windows 11 (64 bit);",
      "Processor: Intel Core i7-12700 or AMD Ryzen 7 7800X3D;",
      "RAM: 16 GB;",
      "Graphics card: GeForce RTX 2060 SUPER, Radeon RX 5700 XT or Arc A770;",
      "Disk space: 85GB (SSD).",
    ],
  },

  {
    id: "5",
    title: "Fortnite",
    release_date: "September 26, 2017",
    genre: "Battle Royale, survival simulator, third person shooter, sandbox",
    developer_publisher: " Epic Games and People Can Fly",
    platform: "PC (Windows), Android",
    multiplayer: "Included",
    version: "28.01, build 30106568",
    size: "59 GB",
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2019/02/fortnite-poster.jpg",
      bg_large:
        "https://wallpapers.com/images/hd/fortnite-background-34h5tua0czqu7u9t.jpg",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2019/02/fortnite-sreenshot-01.png",
      "https://se7en.ws/wp-content/uploads/2019/02/fortnite-sreenshot-02.png",
      "https://se7en.ws/wp-content/uploads/2019/02/fortnite-sreenshot-03.png",
      "https://se7en.ws/wp-content/uploads/2019/02/fortnite-sreenshot-04.png",
    ],
    download_links: {
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOHJkY0VZR0hSWUpOd0VTNkNuVWZnRDBqVnRlU0dOQzIvdmlldz91c3A9c2hhcmluZw==",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvUDRSeFFBcmEjX2hJTXp6M3lWbU5VQUEzYUIxQk04bXRmc3Q1a2dYUVMwZGo4dVE3ZzFVMA==",
      directly:
        "https://se7en.ws/away/aHR0cHM6Ly93d3cuZXBpY2dhbWVzLmNvbS9mb3J0bml0ZS9kb3dubG9hZA==",
    },
    description: [
      "One of the most popular examples of the 'royal battle' genre can rightly be Fortnite, which came out a few months after the resounding success of PUBG. Despite the cartoon graphics and not the best-developed shooting physics, this project earned a huge number of fans in just a year of existence. Now it is one of the most popular games on many streaming platforms. Do you want to join the millions of fans of this game? All you need is to download Fortnite from our site and install the client.",
    ],
    minimum_requirements: [
      "CPU: Intel Core i5-7300U 3.45 GHz",
      "RAM: 8 GB",
      "Video card: Nvidia GTX 960 or AMD R9 280 (2GB)",
      "Operating system: Windows 7 SP1 / 8 / 10 (64-bit systems)",
      "Free disk space: 40 GB",
    ],
    recommended_requirements: [
      "CPU: Intel Core i5 2.8 GHz",
      "RAM: 16 GB",
      "Video card: Nvidia GTX 1080 or AMD Radeon RX 5700 XT",
      "Operating system: Window 10 / 11 (64-bit systems)",
      "Free disk space: 40 GB",
    ],
  },

  {
    id: "6",
    title: "Counter-Strike 2",
    release_date: "September 21, 2023",
    genre: "Multiplayer first-person shooter",
    developer_publisher: "Valve Corporation",
    platform: "PC (Windows)",
    multiplayer: "Included",
    version: "1.39.7.8 (build from 12/7/2023)",
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2023/03/cs2-cover.png",
      bg_large:
        "https://www.desktopbackground.org/download/o/2010/08/12/63140_counter-strike-source-wallpapers-wallpaper_1920x1080_h.jpg",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2023/03/cs2-de_dust2_screenshot-08.jpg",
    ],
    download_links: {
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2RyaXZlL2ZvbGRlcnMvMUEwMjFTcmRjMTlxVTE5dWFXTndUOXVfaXFjQTIxX0pHP3VzcD1zaGFyZV9saW5r",
      torrent: "https://se7en.ws/torrents/cs2_latest.torrent",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvUXg0UjBEU0EjS3ltd0lmVVhlR2NuWF82S1FJWVVBamREaFJDVElDeVRwdmJqWVVTTE5nMA==",
      directly: "https://se7en.ws/files/7l_cs2_setup.exe",
    },
    description: [
      "Counter-Strike 2 is a free CS:GO update that gives players new features and content for years to come. The new architecture (engine) called Source 2 has made the gameplay more responsive, more accurate and more realistic.",
      "Don’t miss your chance to be a part of the new Counter-Strike era, download the game from our website right now and plunge into the exciting world of intense battles, unique strategies and unrivaled skill!",
    ],
    minimum_requirements: [
      "OS: Windows 7 or newer",
      "Processor: Intel or AMD 2.80GHz Dual Core Processor",
      "RAM: 4GB",
      "Graphics Card: NVIDIA GeForce 9600GT or AMD Radeon HD3600",
      "Free Disk Space: 32GB",
    ],
    recommended_requirements: [
      "OS: Windows 10 / 11",
      "Processor: Intel i5-8400 or AMD Ryzen 5 1500X",
      "RAM: 8GB",
      "Graphics Card: Nvidia GTX 1060 or AMD RX 580",
      "Free Disk Space: 32 GB",
    ],
  },

  {
    id: "7",
    title: "Half-Life 2",
    release_date: "Nov 16, 2004",
    genre: "First person shooter",
    developer_publisher: "Valve",
    platform: "PC (Windows)",
    multiplayer: "Included (Deathmatch)",
    version: "build 8491853 from 11/17/2023 – with all episodes (Non-Steam)",
    description: [
      "Half-Life 2” – is a next chapter of the cult “Half-Life” story, which saw the light 6 years after the original was released. Players will again have to control the unchanging Gordon Freeman, who regains consciousness on Earth, and realizes that he is in the near future.    ",
      "All power in this future belongs to an alien government calling itself the Alliance. This Alliance drove all the people on the planet into cities, forcing them to obey. Gordon has to fix this. And although his path is not short, and the goals change quite often, this only gives the game a special originality, making the plot even more interesting.",
    ],
    minimum_requirements: [
      "OS: Windows XP, 7 / 8.1 / 10",
      "Processor: 2 GHz",
      "RAM: 1 GB",
      "Video card: Nvidia GeForce 8, Radeon X1600, Intel HD 3000 or newer",
      "Free disk space: 7 GB",
    ],
    download_links: {
      torrent: "https://se7en.ws/torrents/hl2_latest.torrent",
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOURocXlBdTc3Rmh0dHptZ2JLc0Y2aDhCQms4d3ZfMTMvdmlldz91c3A9c2hhcmluZw==",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvM1ZrRVJRNksjSEJZLW5ZS2FjRHlHV2NZVW1sNDQ4OU1FQjV3aUFGZVFqUVFjVVBzaVZCaw==",
      directly: "https://se7en.ws/files/7l_hl2_setup.exe",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-screenshoot-08.jpg",
    ],
    images: {
      poster:
        "https://se7en.ws/wp-content/uploads/2020/10/half-life-2-cover.jpg",
      bg_large:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwall.alphacoders.com%2Fbig.php%3Fi%3D616245&psig=AOvVaw2LhwHIIOfm7H5TjbS73lOH&ust=1705691841809000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCNiCiJHT54MDFQAAAAAdAAAAABAD",
    },
  },

  {
    id: "8",
    title: "Red Dead Redemption 2",
    release_date: "November 5, 2019",
    genre: "Action, Adventure",
    developer_publisher: "Rockstar Studios & Rockstar Games",
    platform: "PC (Windows)",
    interface_language: "English, French, German, Italian, Russian, etc",
    voice_language: "English for all languages",
    multiplayer: "Included",
    version: "1.0.1436.28",
    description: [
      "Red Dead Redemption 2 — the brainchild of the famous company Rockstar Games, which gave the world such a masterpiece of the gaming industry as GTA. This time, the developers have completely immersed themselves in the spirit of the western, depicting the fictional states of America in the 19th-20th centuries in the game Red Dead Redemption 2.",
      "The game events of RDR 2 will tell about the especially dangerous gang of Dutch Van der Linde, operating in those years. The player controls one of the main characters, Arthur Morgan, and after the story and before the epilogue, John Marston.",
    ],
    minimum_requirements: [
      "Windows 10 (v1803 64-bit)",
      "Intel Core i7-4770K or AMD Ryzen 5 1500X",
      "12 GB",
      "Nvidia GeForce GTX 1060 6 GB or AMD Radeon RX 480 4 GB",
      "150 GB",
    ],
    download_links: {
      torrent: "https://se7en.ws/torrents/rdr2_latest.torrent",
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xTF9ucFowcTNQaE1TZjYtcGVrSW81cWtMWTZyX1Y3dXMvdmlldz91c3A9c2hhcmVfbGluaw==",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvVmhZUXpSRFMjcTRXdzhWUHdfUlJ5U2o5NWRuUWVqelNycXh2S19JN2FoQkNOamEtcXBwYw==",
      directly: "https://se7en.ws/files/7l_rdr2_setup.exe",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2022/10/rdr2-screenshot-08.jpg",
    ],
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2022/10/rdr2-cover.png",
      bg_image:
        "https://www.chromethemer.com/download/hd-wallpapers/rdr2-3840x2160.jpg",
    },
  },

  {
    id: "9",
    title: "Left 4 Dead 2",
    release_date: "November 17, 2009",
    genre: "First person shooter, Survival horror",
    developer_publisher: "Valve Corporation",
    platform: "PC (Windows)",
    interface_language: "English, French, German, Italian, Russian and others",
    voice_language: "English, French, German, Italian, Russian and others",
    multiplayer: "Included",
    version: "2.2.2.9 (The Last Stand) from 9/1/2023",
    description: [
      "Left 4 Dead 2 — telling us the story of survivors group who didn’t have time to evacuate from a city filled with infected residents. Four heroes have to clear their way, going through the crowds of the living dead. As before, the player is given control of one of the four characters, and the bots help in the passage of a series of cards.",
      "The second part of the Left 4 Dead franchise combines the best ideas of the first game also has good even by today’s standards graphics and excellent optimization while it offers cool gameplay. Want to try the game? You can download Left 4 Dead 2 with all the add-ons from our website.",
    ],
    minimum_requirements: [
      "Windows 7 / 8.1 / 10 (32-х or 64-х bit)",
      "Pentium 4 3.0 GHz",
      "2 GB",
      "128 MB, с supporting Shader model 2.0",
      "14 GB",
      "The sound device compatible with DirectX 9.0c",
    ],
    recommended_requirements: [
      "Windows 7 / 8.1 / 10 (64-х bit)",
      "Intel Core 2 Duo 2.GHz",
      "2 GB",
      "256 MB, supporting Shader model 3.0",
      "14 GB",
      "The sound device compatible with DirectX 9.0c",
    ],
    download_links: {
      torrent: "https://se7en.ws/torrents/l4d2_latest.torrent",
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xM1B4TzlQc2NNamVjdXY1UmxySEhSbjVoampNRnRTYUovdmlldz91c3A9c2hhcmluZw==",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvakZ0a1JRN0sjVURMbTMxdUNtOHdaam9CTG1mRi1YdENaeDQ3VmlYN0E4WUplZVRjaVJZVQ==",
      directly: "https://se7en.ws/files/7l_left4dead2_setup.exe",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-08.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-09.jpg",
      "https://se7en.ws/wp-content/uploads/2021/03/l4d2-screenshot-10.jpg",
    ],
    images: {
      poster:
        "https://se7en.ws/wp-content/uploads/2020/01/left-4-dead-2-cover.png",
      bg_image: "https://wallpapercave.com/wp/wp3509481.jpg",
    },
  },

  {
    id: "10",
    title: "American Truck Simulator",
    release_date: "February 2, 2016",
    genre: "Simulator",
    developer_publisher: "SCS Software",
    platform: "PC (Windows)",
    interface_language: "English, French, German, Italian, Russian and others",
    multiplayer: "Available",
    version: "1.49.3.9s from 15/1/2024",
    description: [
      "Simulators are a genre of games that allows us to feel ourselves in the role of a racer, shooter, hunter. But this is all trite, and, at times, has nothing to do with life. Want to play the game of life? Then hurry up to download American Truck Simulator.",
      "The project will teach you how to be a trucker. There is no casualness like in standard racing simulators. American Truck is a combination of strategy and economics. The game will teach you strategic thinking and show you the basics of heavy haulage. The key component is driving, the first person view can help you feel the game.",
    ],
    minimum_requirements: [
      "Windows 7 SP1 (32 bit)",
      "Dual-core 2.4 GHz",
      "6 GB",
      "1 GB, GeForce GTS 450 or Intel HD 4000",
      "20 GB",
    ],
    recommended_requirements: [
      "Windows 7 SP1 / 8.1 / 10/11 (64 bit)",
      "Quad-core 3.0 GHz",
      "8 GB",
      "2 GB, GeForce GTX 760 or better",
      "20 GB",
    ],
    download_links: {
      torrent: "https://se7en.ws/torrents/ats_latest.torrent",
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xQ2RzakFBeGRFbTNIYXlBdElCaDBCNHR0RzItSk9PbjEvdmlldz91c3A9c2hhcmluZw==",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvM2RzQ0RiamEjX3pURWhVZ1RWN2JEN18wRmlEZTVJUk14ZTlUTVRwNzBUUnh5bjQ4X0ptZw==",
      directly: "https://se7en.ws/files/7l_ats_setup.exe",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2021/07/ats-screenshoot-08.jpg",
    ],
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2021/07/ats-cover-495px.jpg",
      bg_image:
        "https://c4.wallpaperflare.com/wallpaper/518/846/489/video-game-american-truck-simulator-wallpaper-preview.jpg",
    },
  },

  {
    id: "11 ",
    title: "Portal 2",
    release_date: "April 11, 2011",
    genre: "Adventure, First Person Puzzle",
    developer_publisher: "Valve",
    platform: "PC",
    interface_language: "Multilingual",
    voice_language: "English, French, German, Italian, Russian and others",
    multiplayer: "Included (Non-Steam)",
    version: "2.0.0.1 UP8 (from 31.01.2022)",
    description: [
      "Portal 2 – is the long-awaited sequel to the game that has won the hearts of many gamers. The unchanging developer Valve Corporation has created a new story, the plot takes place many, many years after the events in the original “Portal”. A red-haired girl named Chell regains consciousness in the bowels of the same research center. Almost immediately, the structure begins to collapse.",
      "At the beginning, Portal 2 does not cause much enthusiasm for the players, because it resembles the first part, but once you move forward a little, then the game changes beyond recognition. There are a lot of changes, but the developer is in no hurry to dump them all at once, but introduces gradually, teaching the player to think in completely different categories. The levels are thought out perfectly: tricky enough to arouse interest, and the desire to strain the convolutions.",
    ],
    minimum_requirements: [
      "Windows XP / 7 / 8.1 / 10",
      "Dual-core from Intel or AMD, 3.0 GHz",
      "2 GB",
      "128 MB Radeon X800 or GeForce 7600 or better",
      "8 GB",
    ],
    download_links: {
      torrent: "https://se7en.ws/torrents/portal2_latest.torrent",
      gdrive:
        "https://se7en.ws/away/aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOVlGZ0w1SFpqVGZHb2N4NVdzU19ISURvUEFQOVlFSkQvdmlldz91c3A9c2hhcmluZw==",
      mega: "https://se7en.ws/away/aHR0cHM6Ly9tZWdhLm56L2ZpbGUvZU5rRWtRelkjRVVHVHV2YlhDYWE5bHFsdkttRURrcERZZlFLRW5DZE1LTmw0VWZJZjk1dw==",
      directly: "https://se7en.ws/files/7l_portal2_setup.exe",
    },
    screenshots: [
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-01.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-02.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-03.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-04.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-05.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-06.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-07.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-08.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-09.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-10.jpg",
      "https://se7en.ws/wp-content/uploads/2021/04/portal-2-screenshoot-11.jpg",
    ],
    images: {
      poster: "https://se7en.ws/wp-content/uploads/2020/10/portal-2-cover.jpg",
      bg_image:
        "https://c4.wallpaperflare.com/wallpaper/181/468/46/portal-game-glados-portal-2-wallpaper-preview.jpg",
    },
  },
];

export { data };
